Feature/new method is empty
OpenAPITools/jackson-databind-nullable pull request #8
Opened 2019-07-01 05:58 UTC by SirWayne

New method is empty for JsonNullable
#7

2019-09-10 09:42 UTC, cbornet commented
Thanks for the PR. I think your previous naming of `isUndefined` was more coherent with the rest of the API. I chose `undefined` instead of `empty` to avoid confusion with Optional.
Can you rename to `isUndefined` ?

2019-11-08 14:49 UTC, SirWayne commented
@cbornet done

2020-11-01 15:55 UTC, cbornet requested changes

2020-11-01 15:55 UTC, cbornet commented on src/test/java/org/openapitools/jackson/nullable/ModuleTestBase.java
> +    protected void assertValueIsPresent(JsonNullable<?> jsonNullable){
Maybe just `assertPresent` ?

2020-11-01 15:55 UTC, cbornet commented on src/test/java/org/openapitools/jackson/nullable/ModuleTestBase.java
> +    protected void assertValueIsEmpty(JsonNullable<?> jsonNullable){
Replace with `assertUndefined`

2020-11-01 15:55 UTC, cbornet commented on src/test/java/org/openapitools/jackson/nullable/PolymorphicJsonNullableTest.java
> +        assertValueIsPresent(fromJson.contained );
Space after `contained` to be removed

2020-11-01 15:57 UTC, cbornet commented
@MelleD I totally forgot about this PR ! I'm so very sorry ! 
I did some comments and it needs to be rebased. Do you still want to work on it ?

2022-07-18 11:44 UTC, closed without merging